version: '3.8'
services:

  # PHP7.4 service
  app:
    build:
      context: .
      dockerfile: Docker/AppDockerfile
    image: php7.4
    container_name: mediapark-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /Docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - mediapark-app-network

networks:
  mediapark-app-network:
    driver: bridge


  
