version: '3.8'
services:

  # PHP7.4 service
  mediapark-app:
    build:
      context: .
      dockerfile: Docker/AppDockerfile
    image: php7.4
    container_name: mediapark-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: mediapark-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /Docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - mediapark-app-network

  #Nginx Service
  mediapark-webserver:
    image: nginx:alpine
    container_name: mediapark-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./Docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - mediapark-app-network

networks:
  mediapark-app-network:
    driver: bridge